# Generated by Django 5.2.8 on 2025-11-05 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название газеты')),
                ('publication_index', models.CharField(max_length=20, unique=True, verbose_name='Индекс издания')),
                ('editor_first_name', models.CharField(max_length=100, verbose_name='Имя редактора')),
                ('editor_last_name', models.CharField(max_length=100, verbose_name='Фамилия редактора')),
                ('editor_middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество редактора')),
                ('price_per_copy', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена экземпляра')),
            ],
            options={
                'verbose_name': 'Газета',
                'verbose_name_plural': 'Газеты',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PostOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Номер почтового отделения')),
                ('address', models.TextField(verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Почтовое отделение',
                'verbose_name_plural': 'Почтовые отделения',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='PrintingHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название типографии')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Типография',
                'verbose_name_plural': 'Типографии',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество экземпляров')),
                ('newspaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.newspaper', verbose_name='Газета')),
                ('post_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.postoffice', verbose_name='Почтовое отделение')),
                ('printing_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.printinghouse', verbose_name='Типография')),
            ],
            options={
                'verbose_name': 'Распределение',
                'verbose_name_plural': 'Распределения',
                'ordering': ['post_office', 'newspaper'],
                'unique_together': {('post_office', 'newspaper', 'printing_house')},
            },
        ),
        migrations.CreateModel(
            name='PrintingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circulation', models.IntegerField(verbose_name='Тираж')),
                ('newspaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.newspaper', verbose_name='Газета')),
                ('printing_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.printinghouse', verbose_name='Типография')),
            ],
            options={
                'verbose_name': 'Тираж',
                'verbose_name_plural': 'Тиражи',
                'ordering': ['-circulation'],
                'unique_together': {('printing_house', 'newspaper')},
            },
        ),
    ]
