# Generated by Django 4.2.16 on 2026-02-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_newspaper_postoffice_printinghouse_distribution_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookeditor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='bookeditor',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookeditor',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='book',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='manager',
        ),
        migrations.AlterUniqueTogether(
            name='contractauthor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='contractauthor',
            name='author',
        ),
        migrations.RemoveField(
            model_name='contractauthor',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='editor',
            name='employee_ptr',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='financialrecord',
            name='related_contract',
        ),
        migrations.RemoveField(
            model_name='financialrecord',
            name='related_order',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='employee_ptr',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='book',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookEditor',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='ContractAuthor',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Editor',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='FinancialRecord',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
