# Generated by Django 4.2.16 on 2026-02-10 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_bookeditor_unique_together_and_more'),
    ]

    operations = [
    ]
